Style/MethodCallWithoutArgsParentheses:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/EmptyElse:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Layout/LineLength:
  Enabled: false
